# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- 'develop'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs: 

- job: Build 
  displayName: 'build'

  steps:
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests for API Template
    inputs:
      command: 'test'
      projects: 'ASP.NetCore-API-UnitTests'
      arguments: '--configuration $(buildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=$(Build.SourcesDirectory)/TestResults/Coverage/'
      publishTestResults: true

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage report'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Build.SourcesDirectory)/**/coverage.cobertura.xml'

  - task: DotNetCoreCLI@2
    displayName: Build API Template
    inputs:
      command: 'build'
      projects: ASP.NetCore-API-Template'
      configuration: '$(buildConfiguration)'
    
  - task: DotNetCoreCLI@2
    displayName: Prepare Publishing
    inputs:
      command: 'publish'
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      publishWebProjects: true
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: Publish
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'API Executable'

  - task: Docker@2
    inputs:
      containerRegistry: 'docker reg connection'
      repository: 'testrepo'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
